AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hello Go Lambda
Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: hello-go-lambda
      Runtime: go1.x
      CodeUri: ./
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
